[versions]
minecraft = "1.16.1"
yarn_mappings = "1.16.1-SNAPSHOT"
fabric_loader = "0.14.24"
loom = "1.4-SNAPSHOT"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn_mappings = { module = "com.github.redlime:yarn", version.ref = "yarn_mappings" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

[plugins]
fabric_loom = { id = "fabric-loom", version.ref = "loom" }
