name: build
on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 21
      - run: |
          chmod +x ./gradlew
          ./gradlew build
      - uses: actions/upload-artifact@v3
        with:
          path: build/libs/*.jar
